FridgeOnline/FridgeOnline/Controllers/ShoppingListController.cs
using Microsoft.AspNet.Identity;
using Repository.Interfaces;
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FridgeOnline.Controllers
{
    [Authorize]
    public class ShoppingListController : Controller
    {
        private readonly IFridge repo;
        private readonly IShoppingList shoppingList;

        public ShoppingListController(IFridge repo, IShoppingList shoppingList)
        {
            this.repo = repo;
            this.shoppingList = shoppingList;
        }

        // GET: ShoppingList
        public ActionResult Index()
        {
            var products = repo.GetProducts();
            string userID = User.Identity.GetUserId();
            products = products.Where(model => model.UserId == userID && model.InShoppingList == true);
            return View(products);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            repo.DeleteProduct(id);

            try
            {
                repo.SaveChanges();
            }
            catch
            {
                return View("Index");
            }

            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Type,Count,TypeOfCountList")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.UserId = User.Identity.GetUserId();
                product.ExpirationDate = null;
                product.InShoppingList = true;

                try
                {
                    repo.AddProduct(product);
                    repo.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(product);
                }
            }

            return View(product);
        }

        [HttpPost]
        public ActionResult MoveProductsToFridge()
        {
            try
            {
                shoppingList.MoveToFridge();
                repo.SaveChanges();
                return RedirectToAction("Index", "Fridge");
            }
            catch
            {
                return View("Index");
            }
        }

        public ActionResult Edit(int id)
        {
            Product product = repo.FindProductById(id);

            if (product == null)
                return HttpNotFound();

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            try
            {
                shoppingList.EditProductInShoppingList(product);
                repo.SaveChanges();
            }
            catch
            {
                ViewBag.Error = true;
                return View("Index");
            }

            ViewBag.Error = false;
            return RedirectToAction("Index");
        }
    }
}

FridgeOnline/FridgeOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fridge Online", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                @if (!User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                }
                
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Fridge", "Index", "Fridge")</li>
                    </ul>

                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Shopping List", "Index", "ShoppingList")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mateusz Bedła, Bartosz Betka</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    
</body>
</html>