FridgeOnline/FridgeOnline/Controllers/FridgeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Repository.DAL;
using Repository.Models;
using Repository.Interfaces;
using Microsoft.AspNet.Identity;
using PagedList;

namespace FridgeOnline.Controllers
{
    [Authorize]
    public class FridgeController : Controller
    {
        private readonly IFridge repo;

        public FridgeController(IFridge repo)
        {
            this.repo = repo;
        }

        // GET: Fridge
        public ActionResult Index(string ProductsSought, int? page)
        {
            IEnumerable<Product> foundProducts;
            string userID = User.Identity.GetUserId();
            int currentPage = page ?? 1;
            int onPage = 5;            

            if (ProductsSought == "")
                ProductsSought = null;

            if (ProductsSought != null)
            {
                foundProducts = repo.GetProducts().Where(s => s.Type == ProductsSought);

                if (foundProducts.Count() == 0)
                {
                    ViewBag.Error = true;
                    return View(foundProducts.OrderBy(o => o.ExpirationDate).ToPagedList<Product>(currentPage, onPage));
                }
            }
            else
                foundProducts = repo.GetProducts().Where(model => model.UserId == userID && model.InShoppingList == false);            

            if (Request.IsAjaxRequest())
                return View(foundProducts.OrderBy(o => o.ExpirationDate).ToPagedList<Product>(currentPage, onPage));

            return View(foundProducts.OrderBy(o => o.ExpirationDate).ToPagedList<Product>(currentPage, onPage));
        }

        // GET: Fridge/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fridge/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Type,Count,TypeOfCountList,ExpirationDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.UserId = User.Identity.GetUserId();

                try
                {
                    repo.AddProduct(product);
                    repo.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(product);
                }
            }

            return View(product);
        }

        // POST: Fridge/Delete
        [HttpPost]
        public ActionResult Delete(int id)
        {
            repo.DeleteProduct(id);

            try
            {
                repo.SaveChanges();
            }
            catch
            {
                return View("Index");
            }
                        
            return RedirectToAction("Index");
        }

        public ActionResult ChangeCountOfProduct(int id)
        {
            var product = repo.FindProductById(id);

            if (product == null)
                return HttpNotFound();

            return View(product);
        }

        [HttpPost]
        public ActionResult ChangeCountOfProduct(Product product)
        {
            repo.DecreaseProductCount(product);

            if (product.Count < 0)
            {
                ViewBag.Error = true;
                return View(product);
            }

            else
            {
                try
                {
                    repo.SaveChanges();
                }
                catch
                {
                    ViewBag.Error = true;
                    return View("Index");
                }
            }

            ViewBag.Error = false;
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            Product product = repo.FindProductById(id);

            if (product == null)
                return HttpNotFound();

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            try
            {
                repo.Edit(product);
                repo.SaveChanges();
            }
            catch
            {
                ViewBag.Error = true;
                return View("Index");
            }


            ViewBag.Error = false;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult MoveToShoppingList(int id)
        {
            repo.MoveToShoppingList(id);

            try
            {
                repo.SaveChanges();
            }
            catch
            {
                return View("Index");
            }

            return RedirectToAction("Index", "ShoppingList");
        }
       
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

FridgeOnline/FridgeOnline/Views/Fridge/ChangeCountOfProduct.cshtml
@model Repository.Models.Product

@{
    ViewBag.Title = "ChangeCountOfProduct";
}

@if (ViewBag.Error == true)
{
    <div class="alert alert-danger" role="alert">
        You don't have enouogh count of this product!!!
        <br /> Try again.
    </div>
}

<h2>Take a product</h2>
<h4>Type: @Model.Type</h4>
<h4>Quantity: @Model.Count @Model.TypeOfCountList</h4>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Type)
        @Html.HiddenFor(model => model.Count)
        @Html.HiddenFor(model => model.TypeOfCountList)
        @Html.HiddenFor(model => model.ExpirationDate)
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.User)
        @Html.HiddenFor(model => model.InShoppingList)

        <div class="form-group">
            @Html.LabelFor(model => model.HowManyDecreaseCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HowManyDecreaseCount, new { htmlAttributes = new { @class = "form-control" } }) 
                @Html.ValidationMessageFor(model => model.HowManyDecreaseCount, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Take" class="btn btn-success" />
        </div>

        <div>
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>
}

FridgeOnline/FridgeOnline/Views/Fridge/Create.cshtml
@model Repository.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Add new product</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfCountList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TypeOfCountList, new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.TypeOfCountList, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FridgeOnline/FridgeOnline/Views/Fridge/Edit.cshtml
@model Repository.Models.Product

@{
    ViewBag.Title = "Edit";
}

@if (ViewBag.Error == true)
{
    <div class="alert alert-danger" role="alert">
        Error: Can't edit product!!!
        <br /> Try again.
    </div>
}

<h2>Edit product</h2>
<h4>Type: @Model.Type</h4>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Type)
        @Html.HiddenFor(model => model.Count)
        @Html.HiddenFor(model => model.TypeOfCountList)
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.User)    
        @Html.HiddenFor(model => model.InShoppingList)    

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FridgeOnline/FridgeOnline/Views/Fridge/Index.cshtml
@model PagedList.IPagedList<Repository.Models.Product>
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/myCssFile.css" rel="stylesheet" />

@{
    ViewBag.Title = "Index";
}

@if (ViewBag.Error == true)
{
    <div class="alert alert-danger" role="alert">
        Error: You don't have this product!!!
    </div>
}

<h2>Products in the fridge</h2>

<p>
    @Html.ActionLink("Add product to fridge", "Create", null, new { @class = "btn btn-primary"})
</p>

<div>
    <form id="search" method="get" , data-ajax="true" data-ajax-target="#productsList" data-ajax-update="#productsList">
        <input id="ProductsSought" , name="ProductsSought" placeholder="Type of product..." style="width: 200px" />
        <input type="submit" value="Search" />
    </form>
    <br /><br />
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Count)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ExpirationDate)
        </th>
        <th>Function</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @if (item.ExpirationDate <= DateTime.Now || item.Count == 0)
        {
            <td class="warning">
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td class="warning">
                @Html.DisplayFor(modelItem => item.Count)
                @Html.DisplayFor(modelItem => item.TypeOfCountList)
            </td>
            <td class="warning">
                @Html.DisplayFor(modelItem => item.ExpirationDate)
            </td>
            <td class="warning">
                @using (Html.BeginForm("MoveToShoppingList", "Fridge", new { id = item.ProductId }, FormMethod.Post))
                {
                    @Html.Hidden("InShoppingList", item.InShoppingList)
                    <input type="submit" value="Move to shopping list" class="btn btn-warning" />
                }

                @using (Html.BeginForm("Delete", "Fridge", new { id = item.ProductId }, FormMethod.Post))
                {
                    @Html.Hidden("ProductId", item.ProductId)
                    <input type="submit" value="Delete" onclick="return confirm('Are you sure you want delete this product?')" class="btn btn-danger" />
                }
            </td>
        }
        else
        {
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
                @Html.DisplayFor(modelItem => item.TypeOfCountList)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpirationDate)
            </td>
            <td>
                @Html.ActionLink("Take", "ChangeCountOfProduct", new { id = item.ProductId }, new { @class = "btn btn-success" }) | 
                @Html.ActionLink("Edit", "Edit", new { id = item.ProductId }, new { @class = "btn btn-primary" }) 

                @using (Html.BeginForm("Delete", "Fridge", new { id = item.ProductId }, FormMethod.Post))
                {
                    @Html.Hidden("ProductId", item.ProductId)
                    <input type="submit" value="Delete" onclick="return confirm('Are you sure you want delete this product?')" class="btn btn-danger" />
                }                                      
            </td>

        }
    </tr>
}

</table>

<div>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) z @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>